CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS owners(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),email text NOT NULL UNIQUE,password_hash text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sessions(token_hash text PRIMARY KEY,owner_id uuid NOT NULL REFERENCES owners(id) ON DELETE CASCADE,expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS pages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),path text NOT NULL UNIQUE,template text NOT NULL,title text NOT NULL,kind text NOT NULL,brief jsonb NOT NULL DEFAULT '{}',draft_revision_id uuid,published_revision_id uuid,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS revisions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),page_id uuid NOT NULL REFERENCES pages(id),content jsonb NOT NULL,validation jsonb NOT NULL DEFAULT '{}',origin text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='pages_draft_fk') THEN ALTER TABLE pages ADD CONSTRAINT pages_draft_fk FOREIGN KEY(draft_revision_id) REFERENCES revisions(id);ALTER TABLE pages ADD CONSTRAINT pages_published_fk FOREIGN KEY(published_revision_id) REFERENCES revisions(id);END IF;END $$;
CREATE TABLE IF NOT EXISTS sources(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),title text NOT NULL,url text,excerpt text NOT NULL,approved boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS facts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),statement text NOT NULL,source_id uuid REFERENCES sources(id),approved boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS settings(key text PRIMARY KEY,value jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS jobs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),page_id uuid NOT NULL REFERENCES pages(id),provider text NOT NULL,model text NOT NULL,status text NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','running','completed','failed','cancelled')),attempts integer NOT NULL DEFAULT 0,lease_token uuid,lease_until timestamptz,next_attempt_at timestamptz NOT NULL DEFAULT now(),base_revision_id uuid,result_revision_id uuid REFERENCES revisions(id),error text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS jobs_one_active_page ON jobs(page_id) WHERE status IN ('queued','running');
CREATE TABLE IF NOT EXISTS job_attempts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),job_id uuid NOT NULL REFERENCES jobs(id),provider text NOT NULL,model text NOT NULL,prompt_version text NOT NULL,usage jsonb,result text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS leads(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),request_id uuid NOT NULL UNIQUE,data jsonb NOT NULL,status text NOT NULL DEFAULT 'New' CHECK(status IN ('New','Qualified','Unqualified','Contacted','Closed')),notes text NOT NULL DEFAULT '',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS rate_limits(key text PRIMARY KEY,count integer NOT NULL,expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS audit_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),owner_id uuid REFERENCES owners(id),action text NOT NULL,entity_id text,details jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS redirects(path text PRIMARY KEY,destination text NOT NULL);
CREATE TABLE IF NOT EXISTS assets(path text PRIMARY KEY,alt text,attribution text);
CREATE INDEX IF NOT EXISTS jobs_poll ON jobs(status,next_attempt_at,lease_until);
CREATE INDEX IF NOT EXISTS revisions_page ON revisions(page_id,created_at DESC);
CREATE INDEX IF NOT EXISTS leads_created ON leads(created_at DESC);
CREATE TABLE IF NOT EXISTS migrations(name text PRIMARY KEY,applied_at timestamptz NOT NULL DEFAULT now());
