import {isDeepStrictEqual} from 'node:util';
import {query,pool} from '../src/db';import {loadSpecifications} from '../src/page-spec-import';import {hubFor,hubChildren,serviceHubs} from '../src/service-hubs';import {validateBlueprint} from '../src/page-spec-schema';import {readAsset} from '../src/production-assets';import {writeFile,mkdir} from 'node:fs/promises';
try{
 const input=await loadSpecifications();const source=new Map(input.pages.map(p=>[p.path,p]));
 const pages=await query(`SELECT p.id,p.path,p.title,p.kind,p.template,p.archived_at,p.draft_revision_id,p.published_revision_id,d.content draft,v.content live,s.specification,s.id spec_id,r.status run_status,r.scope run_scope,r.created_at run_date,r.result_revision_id,r.error run_error FROM pages p LEFT JOIN revisions d ON d.id=p.draft_revision_id LEFT JOIN revisions v ON v.id=p.published_revision_id LEFT JOIN LATERAL(SELECT id,specification FROM page_specs WHERE page_id=p.id ORDER BY created_at DESC LIMIT 1)s ON true LEFT JOIN LATERAL(SELECT status,scope,created_at,result_revision_id,error FROM pipeline_runs WHERE page_id=p.id ORDER BY created_at DESC LIMIT 1)r ON true ORDER BY p.path`);
 const assets=await query('SELECT id,filename FROM generated_assets');const files=new Map<string,boolean>();for(const a of assets){try{await readAsset(a.filename);files.set(a.id,true)}catch{files.set(a.id,false)}}
 const rows=pages.map(p=>{const spec=p.specification;const src=source.get(p.path);const draft=p.draft;const live=p.live;const issues:string[]=[];if(!spec)issues.push('Missing revised specification');else{if(spec.databaseId!==p.id)issues.push('Specification identity mismatch');if(!src)issues.push('Imported specification absent from source CSV');else if(!isDeepStrictEqual(src,spec))issues.push('Imported specification differs from current source');if(draft?.schemaVersion===3){try{validateBlueprint(spec,draft.pageBlueprint)}catch(e){issues.push('Invalid blueprint: '+(e as Error).message)}for(const s of spec.sections){const d=draft.pageSections?.find((x:any)=>x.id===s.id);if(!d){issues.push('Missing draft section '+s.id);continue}if(s.fields.some((k:string)=>!(k in d.fields)))issues.push('Missing exact fields '+s.id);if(s.hero&&!d.asset)issues.push('Draft missing designated hero');if(d.asset&&!files.get(d.asset.id))issues.push('Draft asset file missing '+s.id)}}}
 const styled=(c:any)=>p.path!=="/" || Boolean(hubFor(p.path)||serviceHubs.some(h=>hubChildren(h).some(x=>x.url===p.path))||['/services','/engagement-models','/about','/how-we-work'].includes(p.path)||c?.pageSections?.some((s:any)=>['what-we-deliver','services-grid','service-overview'].includes(s.id)));
 const render=(c:any,published:boolean)=>!c?'None':c.schemaVersion===3?(styled(c)?'V3 shared service theme':'V3 generic/static'):p.path==='/'?'Custom homepage':p.path==='/services'?'Custom service directory':hubFor(p.path)?'Custom service hub':c.schemaVersion===2?'Legacy V2 structured':'Legacy V1';
 return {url:p.path,title:p.title,id:p.id,archived:!!p.archived_at,source_csv:src?.source??'',mapped:!!spec,sections:spec?.sections.length??0,designated_images:spec?.sections.filter((s:any)=>s.hero).length??0,draft_version:draft?.schemaVersion??(draft?1:0),live_version:live?.schemaVersion??(live?1:0),draft_design:render(draft,false),live_design:render(live,true),draft_differs_from_live:p.draft_revision_id!==p.published_revision_id,latest_run:p.run_status??'none',run_scope:p.run_scope??'',run_date:p.run_date?.toISOString()??'',issues:issues.join('; '),next_action:!spec?'Map page specification before V3 regeneration':draft?.schemaVersion!==3?'Generate V3 replacement draft':issues.length?'Review specification/content/asset issues':p.draft_revision_id!==p.published_revision_id?'Review draft and publish manually':!styled(live)?'Align static composition with shared theme':'Mapped and live on shared theme'};});
 await mkdir('research docs/audits',{recursive:true});const cols=Object.keys(rows[0]);const esc=(x:any)=>'"'+String(x??'').replaceAll('"','""')+'"';await writeFile('research docs/audits/page-template-coverage.csv',[cols.map(esc).join(','),...rows.map(r=>cols.map(k=>esc((r as any)[k])).join(','))].join('\r\n'));
 const count=(fn:(r:any)=>boolean)=>rows.filter(fn).length;const sections=[['Missing revised specification',rows.filter(r=>!r.mapped)],['Mapped but draft still legacy',rows.filter(r=>r.mapped&&r.draft_version!==3)],['V3 draft awaiting publication',rows.filter(r=>r.draft_version===3&&r.draft_differs_from_live)],['Published V3 using generic/static styling',rows.filter(r=>r.live_design==='V3 generic/static')],['Mapped specification/content/asset issues',rows.filter(r=>r.mapped&&r.issues)]] as const;
 const report=`# Page generation and template integration audit\n\nChecked ${new Date().toISOString()}. Read-only database audit; no generation or publication performed.\n\n## Summary\n\n|Measure|Count|\n|---|---:|\n|Database page records|${rows.length}|\n|Archived records|${count(r=>r.archived)}|\n|Current CSV unique pages|${input.pages.length}|\n|Imported specifications|${count(r=>r.mapped)}|\n|Missing revised specification|${count(r=>!r.mapped)}|\n|V3 drafts|${count(r=>r.draft_version===3)}|\n|Published V3 pages|${count(r=>r.live_version===3)}|\n|Published V3 shared theme|${count(r=>r.live_design==='V3 shared service theme')}|\n|Published V3 generic/static|${count(r=>r.live_design==='V3 generic/static')}|\n\n## Meaning and limits\n\nA specification mapping enables the new pipeline; it does not migrate existing revisions. V3 adoption requires a generated or edited V3 draft and manual publication. Public routing selects the published revision, not the latest generated result. Missing mappings fall back to legacy generation. Some legacy hubs/homepage have custom modern rendering, so legacy content does not always mean old-looking design. Static V3 pages are supported but do not all inherit the Mobile/Flutter theme. CSV image flags determine whether image tasks exist. No-image specifications are intentional, not asset failures. Blank evidence fields may be intentional.\n\nChecks include database identity, current source/import parity, exact draft section fields, approved blueprint components, designated hero references and persistent asset files. This is a code/database audit, not browser visual approval or a live external-provider test. Existing jobs do not guarantee future provider availability.\n\n## Not integrated / remaining work\n\n${sections.map(([title,list])=>`### ${title} (${list.length})\n\n${list.length?list.map(r=>`- ${r.url} — ${r.next_action}${r.mapped&&r.issues?' · '+r.issues:''}`).join('\n'):'None.'}`).join('\n\n')}\n\n## Complete inventory\n\nSee [page-template-coverage.csv](page-template-coverage.csv) for all records, page IDs, draft/live versions, renderer families, image requirements, latest run state and next action. Categories overlap; do not add their counts.\n`;
 await writeFile('research docs/audits/page-template-coverage.md',report);console.log(report.slice(0,1100));console.log('MAPPED ISSUES',rows.filter(r=>r.mapped&&r.issues).map(r=>({url:r.url,issues:r.issues})));
}finally{await pool().end()}


