const {chromium}=require('C:/Users/KD/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path=require('path');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
 await page.goto('file:///'+path.join(__dirname,'index.html').replace(/\\/g,'/'));
 await page.evaluate(()=>document.fonts.ready);
 await page.locator('img').evaluateAll(images=>images.forEach(img=>img.loading='eager'));
 await page.evaluate(()=>Promise.all(Array.from(document.images,img=>img.decode())));
 if(await page.locator('img').evaluateAll(images=>images.some(img=>!img.complete||img.naturalWidth===0)))throw Error('Image failed to load');
 await page.screenshot({path:path.join(__dirname,'desktop-preview.png'),fullPage:true});
 await page.setViewportSize({width:1440,height:2100});
 await page.screenshot({path:path.join(__dirname,'services-preview.png')});
 await page.setViewportSize({width:1440,height:1000});
 console.log('Desktop overflow:',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
 if(await page.locator('.catalog-links a').count()!==24)throw Error('Service catalogue incomplete');
 await page.locator('[data-filter="grow"]').click();
 if(await page.locator('.catalog-card:visible').count()!==3)throw Error('Service filter failed');
 await page.locator('[data-filter="all"]').click();
 await page.locator('.mega summary').click();
 if(await page.locator('.mega-panel a:visible').count()!==24)throw Error('Mega menu incomplete');
 await page.keyboard.press('Escape');
 await page.locator('.catalog [data-service="SEO"]').first().click();
 if(await page.locator('#service').inputValue()!=='SEO')throw Error('Service selection failed');
 await page.locator('[data-choice="website"]').click();
 if(await page.locator('[data-choice="website"]').getAttribute('aria-pressed')!=='true')throw Error('Business selector state failed');
 await page.locator('#choice-link').click();
 if(await page.locator('#service').inputValue()!=='Website design & development')throw Error('Business selector routing failed');
 await page.setViewportSize({width:390,height:844});
 await page.goto('file:///'+path.join(__dirname,'index.html').replace(/\\/g,'/'));
 await page.locator('img').evaluateAll(images=>images.forEach(img=>img.loading='eager'));
 await page.evaluate(()=>Promise.all(Array.from(document.images,img=>img.decode())));
 await page.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';window.scrollTo(0,0)});
 await page.screenshot({path:path.join(__dirname,'mobile-preview.png'),fullPage:true});
 console.log('Mobile overflow:',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
 await page.locator('.menu').click();
 if(await page.locator('.menu').getAttribute('aria-expanded')!=='true')throw Error('Menu failed');
 await page.locator('nav > a.button[href="#contact"]').click();
 await page.locator('input[name=name]').fill('Preview test');
 await page.locator('input[name=email]').fill('preview@example.com');
 await page.locator('textarea').fill('Testing preview behavior.');
 await page.locator('#service').selectOption('SEO');
 await page.locator('form button').click();
 if(!(await page.locator('.form-status').innerText()).includes('not been sent'))throw Error('Demo status missing');
 console.log('Verified service routing, mobile menu, and honest form preview behavior.');
 for(const width of [320,768,1024]){await page.setViewportSize({width,height:900});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Overflow at '+width);}
 console.log('Also verified 320px, 768px and 1024px widths; catalogue filtering and 24-link mega menu.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
