from pathlib import Path
import re
root=Path(__file__).resolve().parent
source=(root/'index.html').read_text(encoding='utf-8')
head=source[:source.index('<body>')].replace('Software Development, Web Design & Digital Marketing | Netofficials','Custom Software & Web Application Development | Netofficials')
head=head.replace('</head>','<link rel="stylesheet" href="software-led.css"></head>')
head=re.sub(r'<meta name="description"[^>]*>','<meta name="description" content="Custom software, web applications and business websites from an India-based team. Discuss your development project with Netofficials.">',head)
def section(identifier):
 start=source.index('<section class="section',source.index('id="'+identifier+'"')-50)
 return source[start:source.index('</section>',start)+10]
approach=section('approach').replace('new application, a better website or a clearer search strategy','new application or a better website').replace('Build or improve','Develop & review').replace('development or marketing priorities','development priorities').replace('Measure next steps','Launch & evolve').replace('Review the work against your goals and decide what comes next.','Agree acceptance criteria, prepare for handover and discuss ongoing support.')
faq=section('questions')
contact=section('contact').replace('What would you<br>like to build<br><span style="color:var(--indigo)">or grow?</span>','Let’s talk about<br><span style="color:var(--indigo)">your next build.</span>').replace('Tell us what you have in mind. A few details will help us understand the right next conversation.','Share your business problem, the software or website you need, and any timing requirements. We’ll start with the scope.').replace('<option>SEO</option>','<option>Web application development</option><option>SEO</option>')
cards=[('01','Custom software development','Software shaped around the way your business works. Discuss the workflows, integrations and requirements that matter.','Custom software','Discuss custom software'),('02','Web application development','Bring a browser-based application or business portal into focus, from requirements to implementation.','Web application development','Discuss your application'),('03','Website development','Create a clear, useful business website with design and functionality considered together.','Website design & development','Discuss your website')]
cardhtml=''.join(f'<article class="catalog-card"><div class="catalog-top"><span class="catalog-icon" aria-hidden="true">{n}</span><small>DEVELOPMENT</small></div><h3>{title}</h3><p>{description}</p><div class="catalog-links"><a href="#contact" data-service="{service}">{cta}<span aria-hidden="true">↗</span></a></div></article>' for n,title,description,service,cta in cards)
body='''<body><a class="skip" href="#main">Skip to content</a><header><div class="wrap nav"><a href="#main" aria-label="Netofficials home"><img class="logo" src="logo.png" alt="Netofficials" width="3032" height="497"></a><button class="menu" aria-controls="navigation" aria-expanded="false">Menu</button><nav id="navigation" aria-label="Main navigation"><a href="#services">Software & websites</a><a href="#approach">Our approach</a><a href="#marketing">SEO & paid search</a><a class="button" href="#contact" data-service="Custom software">Discuss a project ↗</a></nav></div></header><main id="main">
<div class="hero-shell"><div class="wrap"><section class="hero" aria-labelledby="hero-title"><div><div class="eyebrow">Custom software & web development</div><h1 id="hero-title">Software built<br>around<br><span>your business.</span></h1><p class="intro">Turn your requirements into custom software, web applications and business websites—with an India-based development partner for your next project.</p><div class="actions"><a class="button lime" href="#contact" data-service="Custom software">Discuss your software project ↗</a><a class="button outline" href="#services">Explore development services ↓</a></div><div class="hero-note"><i aria-hidden="true"></i> India-based delivery. Working with global buyers.</div></div><div class="hero-photo"><img src="creative-workspace.png" alt="Illustrative software and website design workspace" width="1536" height="1024" fetchpriority="high"><div class="photo-badge"><i aria-hidden="true"></i> FROM REQUIREMENTS TO DELIVERY</div><div class="hero-caption"><span class="caption-icon" aria-hidden="true">&lt;/&gt;</span><div><b>Your requirements. A clear development scope.</b><small>Software · Web applications · Business websites</small></div></div></div></section><div class="strip"><span>DEVELOPMENT AT THE CORE</span><b>Custom software</b><b>Web applications</b><b>Website development</b></div></div></div>
<section class="section wrap" id="services"><div class="section-head"><div><div class="eyebrow">Development capabilities</div><h2>Start with what<br><span style="color:var(--indigo)">you need to build.</span></h2></div><p>Three clear starting points. Choose the work you need, then define the scope around your business.</p></div><div class="catalog">'''+cardhtml+'''</div></section>
<section class="studio"><div class="wrap studio-grid"><div class="studio-photo"><img src="hero-architecture.png" alt="Conceptual architecture representing a considered foundation" width="1536" height="1024" loading="lazy"><div class="studio-label">A considered foundation for your next stage.</div></div><div><div class="eyebrow">Before the first line of code</div><h2>Get the brief right.<br><span style="color:var(--indigo)">Then build with purpose.</span></h2><p>Begin with the people who will use your software, the work it needs to support, and the systems it needs to connect. Use those answers to define a practical scope.</p><div class="studio-points"><div><b>Business requirements</b><small>Clarify users, workflows and the problem to solve.</small></div><div><b>Delivery expectations</b><small>Agree priorities, responsibilities and milestones.</small></div></div></div></div></section>
'''+approach+'''
<section class="marketing-section" id="marketing"><div class="wrap"><div class="marketing-head"><div><div class="eyebrow">A separate capability, when you need it</div><h2>Already built?<br><span>Let’s help people find it.</span></h2></div><p>SEO and paid search are available as separate engagements or a next step after your website launches. Choose marketing when that is the work you need.</p></div><div class="marketing-cards"><article><h3>Search engine optimization</h3><p>Discuss organic visibility, website priorities and a focused SEO engagement.</p><a href="#contact" data-service="SEO">Discuss SEO ↗</a></article><article><h3>SEM & PPC management</h3><p>Discuss search campaigns, landing pages and how enquiries will be measured.</p><a href="#contact" data-service="SEM & PPC">Discuss paid search ↗</a></article></div></div></section>
'''+faq+contact+'''
</main><footer><div class="wrap"><div class="footer-top"><a href="#main"><img class="footer-logo" src="logo.png" alt="Netofficials" width="3032" height="497" style="height:auto"></a><div class="footer-links"><a href="#services">Software & websites</a><a href="#marketing">SEO & paid search</a><a href="#contact">Contact</a></div></div><div class="footer-bottom"><span>© 2026 Netofficials.</span><span>Custom software. Web applications. Business websites.</span></div></div></footer>
<script>const menu=document.querySelector('.menu'),nav=document.querySelector('nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.focus()}});document.querySelectorAll('[data-service]').forEach(a=>a.addEventListener('click',()=>{document.querySelector('#service').value=a.dataset.service}));document.querySelector('form').addEventListener('submit',e=>{e.preventDefault();document.querySelector('.form-status').textContent='This is a layout preview. Your details have not been sent or saved.'});</script></body></html>'''
(root/'software-led.html').write_text(head+body,encoding='utf-8')
print('Saved software-led comparison draft.')
