from pathlib import Path
import html
p=Path(__file__).with_name('index.html')
t=p.read_text(encoding='utf-8')
groups=[
('build','01','⌘','Custom software','Software built around your business workflows, requirements and next stage of growth.','Custom software',['Custom application development','Web application development','API & system integration','Workflow automation']),
('build','02','</>','Website development','Bring your business online with the right structure, functionality and content experience.','Website design & development',['Business website development','CMS development','Website integrations','Website performance optimization']),
('build','03','◇','Website design','Give visitors a clear path from understanding your business to making an enquiry.','Website design & development',['Responsive website design','Website redesign','UI/UX design','Landing page design']),
('grow','04','◎','Search engine optimization','Connect your business with relevant organic searches through a focused SEO scope.','SEO',['Technical SEO','On-page SEO','Local SEO','SEO audits & strategy']),
('grow','05','↗','SEM & PPC','Plan paid-search campaigns around your audience, landing pages and business goals.','SEM & PPC',['Google Ads management','Search advertising','Remarketing campaigns','Campaign audits & optimization']),
('grow','06','⌁','Search & conversion','Connect search intent, content and enquiry paths across your website and campaigns.','SEO',['Keyword research','SEO content planning','Conversion tracking setup','Landing page optimization']),
]
cards=[]
for category,num,icon,title,desc,service,items in groups:
 links=''.join(f'<a href="#contact" data-service="{html.escape(service)}" data-interest="{html.escape(item)}">{html.escape(item)} <span aria-hidden="true">↗</span></a>' for item in items)
 cards.append(f'<article class="catalog-card" data-category="{category}"><div class="catalog-top"><span class="catalog-icon" aria-hidden="true">{html.escape(icon)}</span><small>{num} / {category.upper()}</small></div><h3>{title}</h3><p>{desc}</p><div class="catalog-links">{links}</div></article>')
catalog='''<section class="section wrap" id="services"><div class="section-head"><div><div class="eyebrow">Explore our services</div><h2>Build. Improve. Get discovered.<br><span style="color:var(--indigo)">Find your next step here.</span></h2></div><p>Explore software, websites and search marketing in detail. Start with a specific need or connect services around a bigger goal.</p></div><div class="service-controls"><div class="service-filters" role="group" aria-label="Filter service groups"><button aria-pressed="true" data-filter="all">All capabilities</button><button aria-pressed="false" data-filter="build">Software & websites</button><button aria-pressed="false" data-filter="grow">Search & marketing</button></div><span class="service-count" aria-live="polite">6 service groups · 24 areas to explore</span></div><div class="catalog">'''+''.join(cards)+'''</div><div class="catalog-end"><p>Not sure which service fits? Start with the business problem.</p><a href="#contact">Help me define the scope ↗</a></div></section>'''
start=t.index('<section class="section wrap" id="services">');end=t.index('<section class="chooser"',start)
t=t[:start]+catalog+t[end:]
start=t.index('<div class="hero-shell">');end=t.index('<section class="section wrap" id="services">',start)
hero='''<div class="hero-shell"><div class="wrap"><section class="hero" aria-labelledby="hero-title"><div><div class="eyebrow">Your digital business. Connected.</div><h1 id="hero-title">Build better.<br>Reach further.<br><span>Grow together.</span></h1><p class="intro">Custom software, website design and search marketing under one roof. Build the digital foundation your business needs—and connect it to your next customer.</p><div class="actions"><a class="button" href="#contact">Discuss your project <span aria-hidden="true">↗</span></a><a class="button outline" href="#services">Explore all services <span aria-hidden="true">↓</span></a></div><div class="hero-tags"><a href="#services">Custom software</a><a href="#services">Web design & development</a><a href="#services">SEO</a><a href="#services">SEM & PPC</a></div></div><div class="hero-illustration" role="img" aria-label="Illustrative business workspace connecting website, software and search. Not a client project."><span class="figure-note">ONE CONNECTED DIGITAL FOUNDATION</span><div class="sphere"></div><div class="dashboard"><div class="dash-head"><b>netofficials / workspace</b><span>● ● ●</span></div><div class="dash-body"><div class="dash-menu"><span></span><span></span><span></span><span></span><span></span></div><div><h3>Your next business chapter.</h3><div class="dash-tiles"><span>01<br><b>Software</b></span><span>02<br><b>Website</b></span><span>03<br><b>Organic search</b></span><span>04<br><b>Paid search</b></span></div><div class="dash-line">IDEA → DIGITAL EXPERIENCE → CUSTOMER</div></div></div></div><span class="floating-label">From a business brief to a connected plan ↗</span></div></section><div class="strip"><span>India-based · Global outlook</span><b>Software engineering</b><b>Digital experiences</b><b>Search visibility</b><b>Customer acquisition</b></div><div class="subnav"><a href="#services">Explore capabilities ↓</a><a href="#solutions">Business needs ↓</a><a href="#approach">Delivery approach ↓</a></div></div></div>'''
t=t[:start]+hero+t[end:]
mega='<details class="mega"><summary>Services</summary><div class="mega-panel">'+''.join('<div><strong>'+g[3]+'</strong>'+''.join(f'<a href="#contact" data-service="{html.escape(g[5])}" data-interest="{html.escape(item)}">{html.escape(item)}</a>' for item in g[6])+'</div>' for g in groups)+'</div></details>'
t=t.replace('<a href="#services">Our services</a>',mega,1)
t=t.replace('<a href="#approach">Our approach</a><a href="#questions">FAQs</a><a class="button"','<a href="#solutions">Business needs</a><a href="#approach">Our approach</a><a class="button"',1)
solutions='''<section class="section wrap" id="solutions"><div class="section-head"><div><div class="eyebrow">Start with the outcome</div><h2>What does your business<br>need to do next?</h2></div><p>Choose a direction. We’ll help you discuss the scope and services it might require.</p></div><div class="next-grid"><article class="next-card"><small>01 / OPERATE BETTER</small><h3>Connect your workflows.</h3><p>Explore custom applications and integrations around how your business works.</p><a href="#contact" data-service="Custom software">Discuss your software needs ↗</a></article><article class="next-card"><small>02 / PRESENT BETTER</small><h3>Improve your digital presence.</h3><p>Discuss website structure, design, content and a clearer path to enquiry.</p><a href="#contact" data-service="Website design & development">Discuss your website ↗</a></article><article class="next-card"><small>03 / REACH FURTHER</small><h3>Connect with new customers.</h3><p>Explore SEO and paid search around the audience and demand you want to reach.</p><a href="#contact" data-service="Development + marketing">Discuss your growth plan ↗</a></article></div></section>'''
t=t.replace('<section class="together">',solutions+'<section class="together">',1)
if 'services-first.css' not in t:t=t.replace('</head>','<link rel="stylesheet" href="services-first.css"></head>')
js='''document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{const filter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelectorAll('.catalog-card').forEach(card=>card.hidden=filter!=='all'&&card.dataset.category!==filter);const count=document.querySelectorAll('.catalog-card:not([hidden])').length;document.querySelector('.service-count').textContent=`${count} service groups · ${count*4} areas to explore`;}));document.querySelectorAll('[data-interest]').forEach(a=>a.addEventListener('click',()=>{document.querySelector('textarea').placeholder='Tell us about your '+a.dataset.interest.toLowerCase()+' needs.';document.querySelector('.mega').open=false;}));document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('.mega').open=false;});document.addEventListener('click',e=>{const mega=document.querySelector('.mega');if(!mega.contains(e.target))mega.open=false;});'''
t=t.replace('</script>',js+'</script>')
p.write_text(t,encoding='utf-8')
print('Services-first redesign: six groups, 24 service areas, mega menu and filters.')
