from pathlib import Path
import re
p=Path(__file__).with_name('index.html');t=p.read_text(encoding='utf-8')
t=re.sub(r'<style>.*?</style>','',t,flags=re.S)
t=re.sub(r'<link rel="stylesheet" href="(?:creative|services-first)\.css">','',t)
t=t.replace('</head>','<link rel="stylesheet" href="modern.css"></head>')
start=t.index('<div class="hero-shell">');end=t.index('<section class="section wrap" id="services">',start)
t=t[:start]+'''<div class="hero-shell"><div class="wrap"><section class="hero" aria-labelledby="hero-title"><div><div class="eyebrow">A digital partner for your next chapter</div><h1 id="hero-title">Great ideas deserve<br>to be built.<br><span>And discovered.</span></h1><p class="intro">We connect custom software, website design and search marketing—so your business can build its digital foundation and reach the people who matter.</p><div class="actions"><a class="button lime" href="#contact">Let’s build something <span aria-hidden="true">↗</span></a><a class="button outline" href="#services">Explore our services <span aria-hidden="true">↓</span></a></div><div class="hero-note"><i aria-hidden="true"></i> India-based delivery. A global outlook.</div></div><div class="hero-photo"><img src="hero-architecture.png" alt="Conceptual architectural image of sculptural ivory and blue buildings" width="1536" height="1024" fetchpriority="high"><div class="photo-badge"><i aria-hidden="true"></i> BUILT FOR WHAT’S NEXT</div><div class="hero-caption"><span class="caption-icon" aria-hidden="true">↗</span><div><b>From your next idea to your next customer.</b><small>Software + websites + search marketing</small></div><span aria-hidden="true">↗</span></div></div></section><div class="strip"><span>ONE CONNECTED DIGITAL PARTNER</span><b>Custom software</b><b>Website design & development</b><b>SEO</b><b>SEM & PPC</b></div></div></div>'''+t[end:]
t=t.replace('Build. Improve. Get discovered.<br><span style="color:var(--indigo)">Find your next step here.</span>','What you need to build.<br><span style="color:var(--indigo)">What you need to grow.</span>')
# Consistent lightweight line icons, rather than mixed typographic symbols.
paths=['<rect x="3" y="4" width="18" height="16" rx="3"/><path d="m9 9-3 3 3 3m6-6 3 3-3 3"/>','<rect x="3" y="4" width="18" height="16" rx="3"/><path d="M3 9h18m-13 5h8"/>','<path d="m14 4 6 6-10 10H4v-6L14 4Zm-7 10 3 3m1-10 6 6"/>','<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6m-15-11h8m-4-4v8"/>','<path d="M4 19V5m0 14h16M8 14l4-4 4 2 5-7m-5 0h5v5"/>','<path d="M3 12h5l3-8 4 16 3-8h3"/>']
icons=iter(paths)
def icon(_):return '<span class="catalog-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">'+next(icons)+'</svg></span>'
t=re.sub(r'<span class="catalog-icon" aria-hidden="true">.*?</span>',icon,t)
studio='''<section class="studio"><div class="wrap studio-grid"><div class="studio-photo"><img src="creative-workspace.png" alt="Illustrative design workspace with laptop, notebook and lime stationery" width="1536" height="1024" loading="lazy"><div class="studio-label">A shared brief. A connected next step.</div></div><div><div class="eyebrow">Development meets discovery</div><h2>A better handoff<br>starts with<br><span style="color:var(--indigo)">one shared vision.</span></h2><p>Your website and software shouldn’t be disconnected from how customers find you. Bring development and search marketing into the same conversation, with scope shaped around your business goal.</p><div class="studio-points"><div><b>Build with purpose</b><small>Connect requirements, design and implementation.</small></div><div><b>Grow with context</b><small>Connect search intent and the path to enquiry.</small></div></div></div></div></section>'''
t=t.replace('<section class="chooser"',studio+'<section class="chooser"',1)
t=t.replace('Ambition, translated<br>into a practical plan.','A thoughtful process.<br>A clear way forward.')
t=t.replace('<a class="button" href="#contact">Let’s talk','<a class="button" href="#contact">Let’s talk')
p.write_text(t,encoding='utf-8')
print('Modern layout rebuilt with consistent typography, line icons and two image-led sections.')
