from pathlib import Path
p=Path(__file__).with_name('index.html')
t=p.read_text(encoding='utf-8')
if 'creative.css' not in t:
    t=t.replace('</style></head>','</style><link rel="stylesheet" href="creative.css"></head>')
    start=t.index('<main id="main"><div class="wrap">')
    end=t.index('<section class="section wrap" id="services">')
    t=t[:start]+'''<main id="main"><div class="hero-shell"><div class="hero-art" aria-hidden="true"></div><div class="wrap"><section class="hero" aria-labelledby="hero-title"><div class="eyebrow">India-based delivery. Global ambition.</div><h1 id="hero-title">Build what’s next.<br><span>Grow what<br>matters.</span></h1><p class="intro">Custom software. Distinctive websites. Search marketing. Connect your next business idea to the customers who need it—with one digital partner.</p><div class="actions"><a class="button" href="#contact">Let’s discuss your next move <span aria-hidden="true">↗</span></a><a class="button outline" href="#services">Explore our capabilities <span aria-hidden="true">↓</span></a></div><div class="hero-note"><i aria-hidden="true"></i> Start with one service. Connect more when you need them.</div></section><div class="strip"><span>From idea to opportunity</span><b>Custom software development</b><b>Website design & development</b><b>SEO</b><b>SEM & PPC</b></div></div><div class="hero-path">YOUR NEXT CHAPTER<strong>BUILD → LAUNCH → GROW</strong></div></div>
'''+t[end:]
    marker='<section class="together">'
    chooser='''<section class="chooser" aria-labelledby="choose-title"><div class="wrap"><div class="chooser-head"><h2 id="choose-title">Where does your<br>next chapter begin?</h2><div class="choice-buttons" role="group" aria-label="Select your business need"><button data-choice="software" aria-pressed="true">Build software</button><button data-choice="website" aria-pressed="false">Create a website</button><button data-choice="search" aria-pressed="false">Reach customers</button></div></div><div class="choice-content"><p id="choice-description" aria-live="polite">Turn a workflow, integration challenge or product idea into a clear development brief. Start with your requirements and the problem you want to solve.</p><a href="#contact" id="choice-link" data-service="Custom software">Discuss software development ↗</a></div></div></section>'''
    t=t.replace(marker,chooser+marker)
    t=t.replace('Two capabilities.<br>One business goal: yours.','Engineering meets<br><span style="color:var(--indigo)">customer acquisition.</span>')
    t=t.replace('Clear scope.<br>A practical next step.','Ambition, translated<br>into a practical plan.')
    js='''const choices={software:['Turn a workflow, integration challenge or product idea into a clear development brief. Start with your requirements and the problem you want to solve.','Discuss software development ↗','Custom software'],website:['Create a business website that communicates your offering and helps visitors take the next step. Discuss design, content, development and launch together.','Discuss your website ↗','Website design & development'],search:['Help the right people find your business. Discuss organic search, paid campaigns and the landing pages that connect interest to an enquiry.','Discuss search marketing ↗','Development + marketing']};document.querySelectorAll('[data-choice]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-choice]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));const [description,label,service]=choices[button.dataset.choice];document.querySelector('#choice-description').textContent=description;const link=document.querySelector('#choice-link');link.textContent=label;link.dataset.service=service;}));'''
    t=t.replace('</script>',js+'</script>')
    p.write_text(t,encoding='utf-8')
print('Creative redesign saved.')
